# Generated by Django 4.0.3 on 2022-06-01 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('DNI', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nombre de usuario')),
                ('fecha_de_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('lugar_de_nacimiento', models.CharField(max_length=50, null=True, verbose_name='Lugar de nacimiento')),
                ('direccion_de_facturacion', models.CharField(max_length=50, null=True, verbose_name='Dirección de facturación')),
                ('genero', models.CharField(max_length=20, null=True, verbose_name='Género')),
                ('correo_electronico', models.EmailField(max_length=254, null=True)),
                ('imagen_de_usuario', models.ImageField(blank=True, null=True, upload_to='crudRoot/', verbose_name='Imagen del usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='InfoRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(default='Administrador', max_length=20, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('crudRoot.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(default='Cliente', max_length=20, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('crudRoot.usuario',),
        ),
        migrations.CreateModel(
            name='HistoricalUsuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('DNI', models.IntegerField(db_index=True, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('username', models.CharField(db_index=True, max_length=20, verbose_name='Nombre de usuario')),
                ('fecha_de_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('lugar_de_nacimiento', models.CharField(max_length=50, null=True, verbose_name='Lugar de nacimiento')),
                ('direccion_de_facturacion', models.CharField(max_length=50, null=True, verbose_name='Dirección de facturación')),
                ('genero', models.CharField(max_length=20, null=True, verbose_name='Género')),
                ('correo_electronico', models.EmailField(max_length=254, null=True)),
                ('imagen_de_usuario', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen del usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
