# Generated by Django 4.0.3 on 2022-04-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudRoot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalusuario',
            old_name='nombreDeUsuario',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='inforoot',
            old_name='NombreDeUsuario',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='inforoot',
            old_name='contraseña',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombreDeUsuario',
            new_name='username',
        ),
    ]
