# Generated by Django 4.0.3 on 2022-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderitem',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
